module.exports =
{
    "login": "melvin-zaldana",
    "id": 12090396,
    "node_id": "MDQ6VXNlcjEyMDkwMzk2",
    "avatar_url": "https://avatars.githubusercontent.com/u/12090396?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/melvin-zaldana",
    "html_url": "https://github.com/melvin-zaldana",
    "followers_url": "https://api.github.com/users/melvin-zaldana/followers",
    "following_url": "https://api.github.com/users/melvin-zaldana/following{/other_user}",
    "gists_url": "https://api.github.com/users/melvin-zaldana/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/melvin-zaldana/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/melvin-zaldana/subscriptions",
    "organizations_url": "https://api.github.com/users/melvin-zaldana/orgs",
    "repos_url": "https://api.github.com/users/melvin-zaldana/repos",
    "events_url": "https://api.github.com/users/melvin-zaldana/events{/privacy}",
    "received_events_url": "https://api.github.com/users/melvin-zaldana/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Melvin Zaldaña",
    "company": null,
    "blog": "www.melvinzaldana.com",
    "location": "Mexico City",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 12,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2015-04-23T20:54:12Z",
    "updated_at": "2021-07-02T15:45:24Z"
  };
  